#Thu Feb 01 05:29:27 UTC 2024
micronaut.application.name: Poke-API
datasources:
  default:
    db-type: mariadb
    dialect: MYSQL
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/pokemon
    username: root
    password: root
liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.xml